Rename fpos_t to avoid libc conflict
Arduino IDE 1.8.19 linux64 raises the following errors:

> SdBaseFile.h:38:8: error: using typedef-name 'fpos_t' after 'struct'
>  struct fpos_t {
>         ^~~~~~
> In file included from Marlin/Marlin.h:10:0,
>                  from Marlin/Marlin_main.cpp:30:
> ~/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/avr/include/stdio.h:950:33: note: 'fpos_t' has a previous declaration here
>  __extension__ typedef long long fpos_t;
>                                  ^~~~~~
> In file included from Marlin/SdBaseFile.cpp:24:0:
> SdBaseFile.h:38:8: error: using typedef-name 'fpos_t' after 'struct'
>  struct fpos_t {
>         ^~~~~~
> In file included from Marlin/Marlin.h:10:0,
>                  from Marlin/SdBaseFile.cpp:21:
> ~/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/avr/include/stdio.h:950:33: note: 'fpos_t' has a previous declaration here
>  __extension__ typedef long long fpos_t;
>                                  ^~~~~~
> Marlin/SdBaseFile.cpp: In member function 'void SdBaseFile::getpos(fpos_t*)':
> SdBaseFile.cpp:298:8: error: request for member 'position' in '* pos', which is of non-class type 'fpos_t {aka long long int}'
>    pos->position = curPosition_;
>         ^~~~~~~~
> SdBaseFile.cpp:299:8: error: request for member 'cluster' in '* pos', which is of non-class type 'fpos_t {aka long long int}'
>    pos->cluster = curCluster_;
>         ^~~~~~~
> In file included from Marlin/SdFile.h:27:0,
>                  from Marlin/SdFile.cpp:23:
> SdBaseFile.h:38:8: error: using typedef-name 'fpos_t' after 'struct'
>  struct fpos_t {
>         ^~~~~~
> In file included from Marlin/Marlin.h:10:0,
>                  from Marlin/SdFile.cpp:20:
> ~/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7/avr/include/stdio.h:950:33: note: 'fpos_t' has a previous declaration here
>  __extension__ typedef long long fpos_t;
>                                  ^~~~~~
> Marlin/SdBaseFile.cpp: In member function 'void SdBaseFile::setpos(fpos_t*)':
> SdBaseFile.cpp:1496:23: error: request for member 'position' in '* pos', which is of non-class type 'fpos_t {aka long long int}'
>    curPosition_ = pos->position;
>                        ^~~~~~~~
> SdBaseFile.cpp:1497:22: error: request for member 'cluster' in '* pos', which is of non-class type 'fpos_t {aka long long int}'
>    curCluster_ = pos->cluster;
>                       ^~~~~~~